"""Generates a formatted PDF lab report from analyzed results."""

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
import io

STATUS_COLORS = {
    "NORMAL": colors.HexColor("#2E7D32"),
    "OUT_OF_RANGE": colors.HexColor("#B26A00"),
    "CRITICAL": colors.HexColor("#C62828"),
    "UNKNOWN_TEST": colors.HexColor("#607D8B"),
}


def build_pdf_report(report_id: str, report: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        topMargin=18 * mm, bottomMargin=18 * mm,
        leftMargin=16 * mm, rightMargin=16 * mm,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleX", parent=styles["Title"], fontSize=18, spaceAfter=2
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"], fontSize=9, textColor=colors.grey
    )

    elements = []
    elements.append(Paragraph("Laboratory Report", title_style))
    elements.append(Paragraph(f"Report ID: {report_id}", meta_style))
    elements.append(Paragraph(f"Generated: {report['created_at']}", meta_style))
    if report.get("signed_by"):
        elements.append(Paragraph(
            f"Signed off by: {report['signed_by']} ({report.get('signed_role','')}) "
            f"on {report.get('signed_at','')}", meta_style
        ))
    else:
        elements.append(Paragraph("Status: PENDING PATHOLOGIST SIGN-OFF", meta_style))
    elements.append(Spacer(1, 8))

    s = report["summary"]
    summary_text = (
        f"Total results: {s['total']}  |  Normal: {s['normal']}  |  "
        f"Out of range: {s['out_of_range']}  |  Critical: {s['critical']}  |  "
        f"Unknown test: {s['unknown']}"
    )
    elements.append(Paragraph(summary_text, styles["Normal"]))
    elements.append(Spacer(1, 10))

    data = [["Patient ID", "Name", "Test", "Value", "Unit", "Normal Range", "Status"]]
    for r in report["results"]:
        data.append([
            r["patient_id"], r.get("patient_name", ""), r["test_name"],
            str(r["value"]), r.get("unit", ""), r.get("normal_range") or "—",
            r["status"].replace("_", " "),
        ])

    table = Table(data, repeatRows=1, colWidths=[22*mm, 26*mm, 26*mm, 16*mm, 16*mm, 30*mm, 26*mm])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#16212B")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F5F7F9")]),
    ]
    for i, r in enumerate(report["results"], start=1):
        color = STATUS_COLORS.get(r["status"], colors.black)
        style_cmds.append(("TEXTCOLOR", (6, i), (6, i), color))
    table.setStyle(TableStyle(style_cmds))
    elements.append(table)

    elements.append(Spacer(1, 14))
    elements.append(Paragraph(
        "Auto-generated by LabCheck. Flagged values require pathologist "
        "review before being released to the patient.", meta_style
    ))

    doc.build(elements)
    return buffer.getvalue()
